tests: Try to fix network sudo tests
Once again our ietf-interfaces tests failed [2, patchset 8]. It seems that despite we
flush addresses on the device that is added as a slave to a bridge they
still remain.

  /home/ci/src/cesnet-gerrit-public/CzechLight/velia/tests/sysrepo_system-ietfinterfaces-sudo.cpp:93:
  TEST CASE:  Test ietf-interfaces and ietf-routing
    Add a bridge

  /home/ci/src/cesnet-gerrit-public/CzechLight/velia/tests/sysrepo_system-ietfinterfaces-sudo.cpp:202: FATAL ERROR: REQUIRE( dataFromSysrepoNoStatistics(client, "/ietf-interfaces:interfaces/interface[name='" + IFACE + "']", sysrepo::Datastore::Operational) == expectedIface ) is NOT correct!
    values: REQUIRE( {
    "/ietf-ip:ipv4": "",
    "/ietf-ip:ipv6": "",
    "/ietf-ip:ipv6/address[ip='fe80::2:2ff:fe02:202']": "",
    "/ietf-ip:ipv6/address[ip='fe80::2:2ff:fe02:202']/ip": "fe80::2:2ff:fe02:202",
    "/ietf-ip:ipv6/address[ip='fe80::2:2ff:fe02:202']/prefix-length": "64",
    "/ietf-ip:ipv6/autoconf": "",
    "/name": "czechlight0",
    "/oper-status": "unknown",
    "/phys-address": "02:02:02:02:02:02",
    "/statistics": "",
    "/type": "iana-if-type:ethernetCsmacd",
  } == {
    "/ietf-ip:ipv4": "",
    "/ietf-ip:ipv6": "",
    "/ietf-ip:ipv6/autoconf": "",
    "/name": "czechlight0",
    "/oper-status": "unknown",
    "/phys-address": "02:02:02:02:02:02",
    "/statistics": "",
    "/type": "iana-if-type:ethernetCsmacd",
  } )

It really seems (jkt was right) that processing of ip deletions by our
netlink watcher is slow. See the excerpt from the logs: At timestamp
44.576 the ip command was started and immediately after our netlink
watcher starts processing changes. The ip command finished at 44.648
and at 44.899 (roughly the previous timestamp +250ms wait time) the
test thread already started asking for the data (timestamp 44.906).
But the netlink watcher has not yet processed all the data because at
time 44.927 it has still yet to remove another address from sysrepo.

  44.576 [18718 main T] exec: /usr/bin/sudo /sbin/ip addr flush dev czechlight0
  44.645 [18902 system T] Netlink update on address of link 'czechlight0', action DEL
  44.645 [18902 main T] Processing node deletion /ietf-interfaces:interfaces/interface[name='czechlight0']/ietf-ip:ipv4/address[ip='192.0.2.1']
  44.648 [18718 main T] /usr/bin/sudo /sbin/ip exited
  44.839 [18902 system T] Netlink update on address of link 'czechlight0', action DEL
  44.899 [18718 main E] dataFrom /ietf-interfaces:interfaces/interface[name='czechlight0']
  44.906 [18718 sysrepo I] Published event "operational get" "/ietf-interfaces:interfaces/interface/statistics" with ID 5.
  44.907 [18903 sysrepo I] Processing "ietf-interfaces" "operational get" event with ID 5.
  44.927 [18902 system T] Netlink update on address of link 'czechlight0', action DEL

I have the increased the wait time for netlink to pick up changes done
by the ip command.

Also, ip command seem to have an option "-loops" that "specifies maximum
number of loops the 'ip address flush' logic will attempt before giving
up.  (...) Zero (0) means loop until all addresses are removed." [2].
We might want this too: Don't continue unless you flushed the addresses.
Worst case is the test gets stuck in a loop but ctest sets timeout for
tests so it will get killed eventually.

[1] https://www.man7.org/linux/man-pages/man8/ip.8.html
[2] https://gerrit.cesnet.cz/c/CzechLight/dependencies/+/5976

Change-Id: I5fc04588a0e8b1b936b58bb79dd4a0d3a433bb18