tests: Fix network sudo tests
Once again our ietf-interfaces tests failed [2, patchset 8]. It seems that despite we
flush addresses on the device that is added as a slave to a bridge they
still remain.

  2023-01-16 11:17:45.465335 | w | /home/ci/src/cesnet-gerrit-public/CzechLight/velia/tests/sysrepo_system-ietfinterfaces-sudo.cpp:93:
  2023-01-16 11:17:45.465347 | w | TEST CASE:  Test ietf-interfaces and ietf-routing
  2023-01-16 11:17:45.465359 | w |   Add a bridge
  2023-01-16 11:17:45.465371 | w |
  2023-01-16 11:17:45.465390 | w | /home/ci/src/cesnet-gerrit-public/CzechLight/velia/tests/sysrepo_system-ietfinterfaces-sudo.cpp:202: FATAL ERROR: REQUIRE( dataFromSysrepoNoStatistics(client, "/ietf-interfaces:interfaces/interface[name='" + IFACE + "']", sysrepo::Datastore::Operational) == expectedIface ) is NOT correct!
  2023-01-16 11:17:45.465406 | w |   values: REQUIRE( {
  2023-01-16 11:17:45.465418 | w |   "/ietf-ip:ipv4": "",
  2023-01-16 11:17:45.465430 | w |   "/ietf-ip:ipv6": "",
  2023-01-16 11:17:45.465442 | w |   "/ietf-ip:ipv6/address[ip='fe80::2:2ff:fe02:202']": "",
  2023-01-16 11:17:45.465453 | w |   "/ietf-ip:ipv6/address[ip='fe80::2:2ff:fe02:202']/ip": "fe80::2:2ff:fe02:202",
  2023-01-16 11:17:45.465465 | w |   "/ietf-ip:ipv6/address[ip='fe80::2:2ff:fe02:202']/prefix-length": "64",
  2023-01-16 11:17:45.465476 | w |   "/ietf-ip:ipv6/autoconf": "",
  2023-01-16 11:17:45.465514 | w |   "/name": "czechlight0",
  2023-01-16 11:17:45.465541 | w |   "/oper-status": "unknown",
  2023-01-16 11:17:45.465553 | w |   "/phys-address": "02:02:02:02:02:02",
  2023-01-16 11:17:45.465565 | w |   "/statistics": "",
  2023-01-16 11:17:45.465576 | w |   "/type": "iana-if-type:ethernetCsmacd",
  2023-01-16 11:17:45.465588 | w | } == {
  2023-01-16 11:17:45.465600 | w |   "/ietf-ip:ipv4": "",
  2023-01-16 11:17:45.465611 | w |   "/ietf-ip:ipv6": "",
  2023-01-16 11:17:45.465622 | w |   "/ietf-ip:ipv6/autoconf": "",
  2023-01-16 11:17:45.465634 | w |   "/name": "czechlight0",
  2023-01-16 11:17:45.465645 | w |   "/oper-status": "unknown",
  2023-01-16 11:17:45.465656 | w |   "/phys-address": "02:02:02:02:02:02",
  2023-01-16 11:17:45.465674 | w |   "/statistics": "",
  2023-01-16 11:17:45.465686 | w |   "/type": "iana-if-type:ethernetCsmacd",
  2023-01-16 11:17:45.465697 | w | } )
  2023-01-16 11:17:45.465709 | w |

ip command seem to have an option "-loops" that "specifies maximum number
of loops the 'ip address flush' logic will attempt before giving up.
(...)
Zero (0) means loop until all addresses are removed." [2].

This might be the thing we need.

[1] https://www.man7.org/linux/man-pages/man8/ip.8.html
[2] https://gerrit.cesnet.cz/c/CzechLight/dependencies/+/5976

Change-Id: I5fc04588a0e8b1b936b58bb79dd4a0d3a433bb18