Fix build on clang 11 with libc++
Here's the error message that I was getting on my NixOS:

 /home/jkt/work/cesnet/gerrit/CzechLight/velia/src/firewall/Firewall.cpp:51:26: error: no viable constructor or deduction guide for deduction of template arguments of 'array'
     constexpr std::array skippedNodes{
                          ^
 /nix/store/vk8ynr4hj2a8w7g1b9m8wknzj39iiv4x-libc++-11.0.1/include/c++/v1/__tuple:219:64: note: candidate function template not viable: requires 1 argument, but 10 were provided
 template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                                ^
 /nix/store/vk8ynr4hj2a8w7g1b9m8wknzj39iiv4x-libc++-11.0.1/include/c++/v1/__tuple:219:64: note: candidate function template not viable: requires 0 arguments, but 10 were provided

I have no idea how come this is passing in the CI because it is also
supposed to use these versions of the compiler + stdlib.

Change-Id: Ib323e14547e56d6df5f9f16083c443f11b53bb67